-- Initial schema for NEPSE tracker and Supabase integration.
-- This file is intended for local CLI usage via:
--   npx supabase start
--   npx supabase db push

create table if not exists nepse_live_prices (
    symbol text primary key,
    ltp numeric,
    point_change numeric,
    percent_change numeric,
    total_qty numeric,
    updated_at timestamptz default now()
);

create table if not exists nepse_market_status (
    id int primary key default 1,
    is_open boolean,
    updated_at timestamptz default now(),
    constraint single_row check (id = 1)
);

insert into nepse_market_status (id, is_open)
values (1, false)
on conflict (id) do nothing;

alter table nepse_live_prices enable row level security;
alter table nepse_market_status enable row level security;

drop policy if exists "Public read access" on nepse_live_prices;
create policy "Public read access" on nepse_live_prices
    for select using (true);

drop policy if exists "Public read access" on nepse_market_status;
create policy "Public read access" on nepse_market_status
    for select using (true);

create table if not exists nepse_price_history (
    id bigint generated by default as identity primary key,
    symbol text not null,
    ltp numeric,
    point_change numeric,
    percent_change numeric,
    total_qty numeric,
    recorded_at timestamptz default now()
);

create index if not exists idx_history_symbol_time
    on nepse_price_history(symbol, recorded_at);

alter table nepse_price_history enable row level security;

drop policy if exists "Public read access" on nepse_price_history;
create policy "Public read access" on nepse_price_history
    for select using (true);

create table if not exists symbol_signal (
    symbol text primary key,
    label text not null,
    sma5 numeric,
    sma20 numeric,
    rsi14 numeric,
    volume_spike_pct numeric,
    note text,
    updated_at timestamptz default now()
);

alter table symbol_signal enable row level security;

drop policy if exists "Public read access" on symbol_signal;
create policy "Public read access" on symbol_signal
    for select using (true);

create table if not exists accounts (
    id bigint generated by default as identity primary key,
    name text not null,
    boid text not null unique,
    created_at timestamptz default now()
);

create table if not exists holdings (
    id bigint generated by default as identity primary key,
    account_id bigint not null references accounts(id) on delete cascade,
    symbol text not null,
    quantity numeric not null default 0,
    avg_cost numeric,
    last_updated timestamptz default now(),
    unique(account_id, symbol)
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    account_id bigint not null references accounts(id) on delete cascade,
    symbol text not null,
    type text not null check (type in ('buy', 'sell')),
    quantity numeric not null,
    price numeric not null,
    date date not null,
    created_at timestamptz default now()
);

create index if not exists idx_holdings_account_symbol
    on holdings(account_id, symbol);
create index if not exists idx_transactions_account_symbol
    on transactions(account_id, symbol, date);

alter table accounts enable row level security;
alter table holdings enable row level security;
alter table transactions enable row level security;

drop policy if exists "Public read access" on accounts;
create policy "Public read access" on accounts
    for select using (true);

drop policy if exists "Public read access" on holdings;
create policy "Public read access" on holdings
    for select using (true);

drop policy if exists "Public read access" on transactions;
create policy "Public read access" on transactions
    for select using (true);

create table if not exists ipo_alerts (
    symbol text primary key,
    company_name text not null,
    open_date date,
    close_date date,
    shares_offered bigint default 0,
    share_type text not null default 'ordinary',
    updated_at timestamptz default now()
);

create index if not exists idx_ipo_close_date
    on ipo_alerts(close_date);

alter table ipo_alerts enable row level security;

drop policy if exists "Public read access" on ipo_alerts;
create policy "Public read access" on ipo_alerts
    for select using (true);

create table if not exists telegram_subscribers (
    chat_id text primary key,
    account_id bigint not null references accounts(id) on delete cascade,
    created_at timestamptz default now()
);

create index if not exists idx_telegram_account
    on telegram_subscribers(account_id);

alter table telegram_subscribers enable row level security;

drop policy if exists "Public read access" on telegram_subscribers;
create policy "Public read access" on telegram_subscribers
    for select using (true);
